#!/bin/bash

set -e

template='{{range .data.viewer.pullRequests.nodes -}}
{{tablerow (printf "#%v" .number | autocolor "green") .title (.reviewDecision | autocolor "yellow") (.url | autocolor "cyan") }}
{{end}}
{{tablerender}}'

query='query {
    viewer {
        pullRequests(first: 100, states: OPEN, orderBy: {field: UPDATED_AT, direction: DESC}) {
            nodes {
                number
                title
                reviewDecision
                url
            }
        }
    }
}'

exec gh api graphql --paginate -f query="$query" -t "$template"